apiVersion: v1
kind: Service
metadata:
  name: {{ include "timekeeper.fullname" . }}
  labels:
    {{- include "timekeeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "timekeeper.selectorLabels" . | nindent 4 }}
