// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    *int    `json:"code,omitempty"`
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Event defines model for Event.
type Event struct {
	Description    *string `json:"description,omitempty"`
	Id             *string `json:"id,omitempty"`
	OrganisationId *string `json:"organisationId,omitempty"`
	Title          *string `json:"title,omitempty"`
}

// Location defines model for Location.
type Location struct {
	Address *string `json:"address,omitempty"`
	Id      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// Member defines model for Member.
type Member struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Role *string `json:"role,omitempty"`
}

// Organisation defines model for Organisation.
type Organisation struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

// OrganisationDetail defines model for OrganisationDetail.
type OrganisationDetail struct {
	Events  *[]Event  `json:"events,omitempty"`
	Id      *string   `json:"id,omitempty"`
	Members *[]Member `json:"members,omitempty"`
	Name    *string   `json:"name,omitempty"`
	Slug    *string   `json:"slug,omitempty"`
}

// Room defines model for Room.
type Room struct {
	Capacity   *int    `json:"capacity,omitempty"`
	Id         *string `json:"id,omitempty"`
	LocationId *string `json:"locationId,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// ScheduleEntry defines model for ScheduleEntry.
type ScheduleEntry struct {
	End        *time.Time `json:"end,omitempty"`
	EventId    *string    `json:"eventId,omitempty"`
	Room       *Room      `json:"room,omitempty"`
	Start      *time.Time `json:"start,omitempty"`
	TimeslotId *string    `json:"timeslotId,omitempty"`
}

// Timeslot defines model for Timeslot.
type Timeslot struct {
	End     *time.Time `json:"end,omitempty"`
	EventId *string    `json:"eventId,omitempty"`
	Id      *string    `json:"id,omitempty"`
	RoomId  *string    `json:"roomId,omitempty"`
	Start   *time.Time `json:"start,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = Event

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = Event

// CreateTimeslotJSONRequestBody defines body for CreateTimeslot for application/json ContentType.
type CreateTimeslotJSONRequestBody = Timeslot

// UpdateTimeslotJSONRequestBody defines body for UpdateTimeslot for application/json ContentType.
type UpdateTimeslotJSONRequestBody = Timeslot

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = Location

// UpdateLocationJSONRequestBody defines body for UpdateLocation for application/json ContentType.
type UpdateLocationJSONRequestBody = Location

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = Room

// UpdateRoomJSONRequestBody defines body for UpdateRoom for application/json ContentType.
type UpdateRoomJSONRequestBody = Room

// CreateOrgJSONRequestBody defines body for CreateOrg for application/json ContentType.
type CreateOrgJSONRequestBody = Organisation

// UpdateOrgJSONRequestBody defines body for UpdateOrg for application/json ContentType.
type UpdateOrgJSONRequestBody = Organisation

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create an event
	// (POST /event)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// Remove a location from an event
	// (DELETE /event/location/{locationID})
	RemoveEventLocation(w http.ResponseWriter, r *http.Request, locationID int)
	// Add a location to an event
	// (PUT /event/location/{locationID})
	AddEventLocation(w http.ResponseWriter, r *http.Request, locationID int)
	// Get event details
	// (GET /event/{eventID})
	GetEvent(w http.ResponseWriter, r *http.Request, eventID int)
	// Update an event
	// (PUT /event/{eventID})
	UpdateEvent(w http.ResponseWriter, r *http.Request, eventID int)
	// Get room schedule for an event
	// (GET /event/{eventID}/room/{roomID}/schedule)
	GetEventRoomSchedule(w http.ResponseWriter, r *http.Request, eventID float32, roomID float32)
	// Get schedule for an event
	// (GET /event/{eventID}/schedule)
	GetEventSchedule(w http.ResponseWriter, r *http.Request, eventID int)
	// Create a timeslot for an event
	// (POST /event/{eventID}/timeslot)
	CreateTimeslot(w http.ResponseWriter, r *http.Request, eventID int)
	// Get a timeslot
	// (GET /event/{eventID}/timeslot/{timeslotID})
	GetTimeslot(w http.ResponseWriter, r *http.Request, eventID int, timeslotID int)
	// Update a timeslot
	// (PUT /event/{eventID}/timeslot/{timeslotID})
	UpdateTimeslot(w http.ResponseWriter, r *http.Request, eventID int, timeslotID int)
	// Get user schedule for an event
	// (GET /event/{eventID}/user/{userID}/schedule)
	GetEventUserSchedule(w http.ResponseWriter, r *http.Request, eventID float32, userID float32)
	// List all events
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request)
	// Create a location
	// (POST /location)
	CreateLocation(w http.ResponseWriter, r *http.Request)
	// Get a location
	// (GET /location/{locationID})
	GetLocation(w http.ResponseWriter, r *http.Request, locationID int)
	// Update a location
	// (PUT /location/{locationID})
	UpdateLocation(w http.ResponseWriter, r *http.Request, locationID int)
	// Create a room
	// (POST /location/{locationID}/room)
	CreateRoom(w http.ResponseWriter, r *http.Request, locationID float32)
	// Delete a room
	// (DELETE /location/{locationID}/room/{roomID})
	DeleteRoom(w http.ResponseWriter, r *http.Request, locationID float32, roomID float32)
	// Get a room
	// (GET /location/{locationID}/room/{roomID})
	GetRoom(w http.ResponseWriter, r *http.Request, locationID float32, roomID float32)
	// Update a room
	// (PUT /location/{locationID}/room/{roomID})
	UpdateRoom(w http.ResponseWriter, r *http.Request, locationID float32, roomID float32)
	// Get Locations
	// (GET /locations)
	GetLocations(w http.ResponseWriter, r *http.Request)
	// Create an organisation
	// (POST /org)
	CreateOrg(w http.ResponseWriter, r *http.Request)
	// Delete an organisation
	// (DELETE /org/{org})
	DeleteOrg(w http.ResponseWriter, r *http.Request, org int)
	// Get organisation details
	// (GET /org/{org})
	GetOrg(w http.ResponseWriter, r *http.Request, org int)
	// Update an organisation
	// (PUT /org/{org})
	UpdateOrg(w http.ResponseWriter, r *http.Request, org int)
	// Get events for an organisation
	// (GET /org/{org}/events)
	GetOrgEvents(w http.ResponseWriter, r *http.Request, org int)
	// Get members of an organisation
	// (GET /org/{org}/members)
	GetOrgMembers(w http.ResponseWriter, r *http.Request, org int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create an event
// (POST /event)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a location from an event
// (DELETE /event/location/{locationID})
func (_ Unimplemented) RemoveEventLocation(w http.ResponseWriter, r *http.Request, locationID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a location to an event
// (PUT /event/location/{locationID})
func (_ Unimplemented) AddEventLocation(w http.ResponseWriter, r *http.Request, locationID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get event details
// (GET /event/{eventID})
func (_ Unimplemented) GetEvent(w http.ResponseWriter, r *http.Request, eventID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an event
// (PUT /event/{eventID})
func (_ Unimplemented) UpdateEvent(w http.ResponseWriter, r *http.Request, eventID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get room schedule for an event
// (GET /event/{eventID}/room/{roomID}/schedule)
func (_ Unimplemented) GetEventRoomSchedule(w http.ResponseWriter, r *http.Request, eventID float32, roomID float32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get schedule for an event
// (GET /event/{eventID}/schedule)
func (_ Unimplemented) GetEventSchedule(w http.ResponseWriter, r *http.Request, eventID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a timeslot for an event
// (POST /event/{eventID}/timeslot)
func (_ Unimplemented) CreateTimeslot(w http.ResponseWriter, r *http.Request, eventID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a timeslot
// (GET /event/{eventID}/timeslot/{timeslotID})
func (_ Unimplemented) GetTimeslot(w http.ResponseWriter, r *http.Request, eventID int, timeslotID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a timeslot
// (PUT /event/{eventID}/timeslot/{timeslotID})
func (_ Unimplemented) UpdateTimeslot(w http.ResponseWriter, r *http.Request, eventID int, timeslotID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user schedule for an event
// (GET /event/{eventID}/user/{userID}/schedule)
func (_ Unimplemented) GetEventUserSchedule(w http.ResponseWriter, r *http.Request, eventID float32, userID float32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all events
// (GET /events)
func (_ Unimplemented) GetEvents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a location
// (POST /location)
func (_ Unimplemented) CreateLocation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a location
// (GET /location/{locationID})
func (_ Unimplemented) GetLocation(w http.ResponseWriter, r *http.Request, locationID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a location
// (PUT /location/{locationID})
func (_ Unimplemented) UpdateLocation(w http.ResponseWriter, r *http.Request, locationID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a room
// (POST /location/{locationID}/room)
func (_ Unimplemented) CreateRoom(w http.ResponseWriter, r *http.Request, locationID float32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a room
// (DELETE /location/{locationID}/room/{roomID})
func (_ Unimplemented) DeleteRoom(w http.ResponseWriter, r *http.Request, locationID float32, roomID float32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a room
// (GET /location/{locationID}/room/{roomID})
func (_ Unimplemented) GetRoom(w http.ResponseWriter, r *http.Request, locationID float32, roomID float32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a room
// (PUT /location/{locationID}/room/{roomID})
func (_ Unimplemented) UpdateRoom(w http.ResponseWriter, r *http.Request, locationID float32, roomID float32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Locations
// (GET /locations)
func (_ Unimplemented) GetLocations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an organisation
// (POST /org)
func (_ Unimplemented) CreateOrg(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an organisation
// (DELETE /org/{org})
func (_ Unimplemented) DeleteOrg(w http.ResponseWriter, r *http.Request, org int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get organisation details
// (GET /org/{org})
func (_ Unimplemented) GetOrg(w http.ResponseWriter, r *http.Request, org int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an organisation
// (PUT /org/{org})
func (_ Unimplemented) UpdateOrg(w http.ResponseWriter, r *http.Request, org int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get events for an organisation
// (GET /org/{org}/events)
func (_ Unimplemented) GetOrgEvents(w http.ResponseWriter, r *http.Request, org int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get members of an organisation
// (GET /org/{org}/members)
func (_ Unimplemented) GetOrgMembers(w http.ResponseWriter, r *http.Request, org int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveEventLocation operation middleware
func (siw *ServerInterfaceWrapper) RemoveEventLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationID" -------------
	var locationID int

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", chi.URLParam(r, "locationID"), &locationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveEventLocation(w, r, locationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddEventLocation operation middleware
func (siw *ServerInterfaceWrapper) AddEventLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationID" -------------
	var locationID int

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", chi.URLParam(r, "locationID"), &locationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddEventLocation(w, r, locationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventID" -------------
	var eventID int

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", chi.URLParam(r, "eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, eventID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventID" -------------
	var eventID int

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", chi.URLParam(r, "eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, eventID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventRoomSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetEventRoomSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventID" -------------
	var eventID float32

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", chi.URLParam(r, "eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventID", Err: err})
		return
	}

	// ------------- Path parameter "roomID" -------------
	var roomID float32

	err = runtime.BindStyledParameterWithOptions("simple", "roomID", chi.URLParam(r, "roomID"), &roomID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventRoomSchedule(w, r, eventID, roomID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetEventSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventID" -------------
	var eventID int

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", chi.URLParam(r, "eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventSchedule(w, r, eventID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTimeslot operation middleware
func (siw *ServerInterfaceWrapper) CreateTimeslot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventID" -------------
	var eventID int

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", chi.URLParam(r, "eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTimeslot(w, r, eventID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimeslot operation middleware
func (siw *ServerInterfaceWrapper) GetTimeslot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventID" -------------
	var eventID int

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", chi.URLParam(r, "eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventID", Err: err})
		return
	}

	// ------------- Path parameter "timeslotID" -------------
	var timeslotID int

	err = runtime.BindStyledParameterWithOptions("simple", "timeslotID", chi.URLParam(r, "timeslotID"), &timeslotID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeslotID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimeslot(w, r, eventID, timeslotID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTimeslot operation middleware
func (siw *ServerInterfaceWrapper) UpdateTimeslot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventID" -------------
	var eventID int

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", chi.URLParam(r, "eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventID", Err: err})
		return
	}

	// ------------- Path parameter "timeslotID" -------------
	var timeslotID int

	err = runtime.BindStyledParameterWithOptions("simple", "timeslotID", chi.URLParam(r, "timeslotID"), &timeslotID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeslotID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTimeslot(w, r, eventID, timeslotID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventUserSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetEventUserSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventID" -------------
	var eventID float32

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", chi.URLParam(r, "eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventID", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID float32

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventUserSchedule(w, r, eventID, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLocation operation middleware
func (siw *ServerInterfaceWrapper) CreateLocation(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLocation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocation operation middleware
func (siw *ServerInterfaceWrapper) GetLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationID" -------------
	var locationID int

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", chi.URLParam(r, "locationID"), &locationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocation(w, r, locationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLocation operation middleware
func (siw *ServerInterfaceWrapper) UpdateLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationID" -------------
	var locationID int

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", chi.URLParam(r, "locationID"), &locationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLocation(w, r, locationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoom operation middleware
func (siw *ServerInterfaceWrapper) CreateRoom(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationID" -------------
	var locationID float32

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", chi.URLParam(r, "locationID"), &locationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoom(w, r, locationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRoom operation middleware
func (siw *ServerInterfaceWrapper) DeleteRoom(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationID" -------------
	var locationID float32

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", chi.URLParam(r, "locationID"), &locationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationID", Err: err})
		return
	}

	// ------------- Path parameter "roomID" -------------
	var roomID float32

	err = runtime.BindStyledParameterWithOptions("simple", "roomID", chi.URLParam(r, "roomID"), &roomID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRoom(w, r, locationID, roomID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoom operation middleware
func (siw *ServerInterfaceWrapper) GetRoom(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationID" -------------
	var locationID float32

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", chi.URLParam(r, "locationID"), &locationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationID", Err: err})
		return
	}

	// ------------- Path parameter "roomID" -------------
	var roomID float32

	err = runtime.BindStyledParameterWithOptions("simple", "roomID", chi.URLParam(r, "roomID"), &roomID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoom(w, r, locationID, roomID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRoom operation middleware
func (siw *ServerInterfaceWrapper) UpdateRoom(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationID" -------------
	var locationID float32

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", chi.URLParam(r, "locationID"), &locationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationID", Err: err})
		return
	}

	// ------------- Path parameter "roomID" -------------
	var roomID float32

	err = runtime.BindStyledParameterWithOptions("simple", "roomID", chi.URLParam(r, "roomID"), &roomID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRoom(w, r, locationID, roomID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocations operation middleware
func (siw *ServerInterfaceWrapper) GetLocations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrg operation middleware
func (siw *ServerInterfaceWrapper) CreateOrg(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrg(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrg operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrg(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "org" -------------
	var org int

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrg(w, r, org)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrg operation middleware
func (siw *ServerInterfaceWrapper) GetOrg(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "org" -------------
	var org int

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrg(w, r, org)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrg operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrg(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "org" -------------
	var org int

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrg(w, r, org)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrgEvents operation middleware
func (siw *ServerInterfaceWrapper) GetOrgEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "org" -------------
	var org int

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrgEvents(w, r, org)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrgMembers operation middleware
func (siw *ServerInterfaceWrapper) GetOrgMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "org" -------------
	var org int

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrgMembers(w, r, org)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/event", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/event/location/{locationID}", wrapper.RemoveEventLocation)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/event/location/{locationID}", wrapper.AddEventLocation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event/{eventID}", wrapper.GetEvent)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/event/{eventID}", wrapper.UpdateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event/{eventID}/room/{roomID}/schedule", wrapper.GetEventRoomSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event/{eventID}/schedule", wrapper.GetEventSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/event/{eventID}/timeslot", wrapper.CreateTimeslot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event/{eventID}/timeslot/{timeslotID}", wrapper.GetTimeslot)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/event/{eventID}/timeslot/{timeslotID}", wrapper.UpdateTimeslot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event/{eventID}/user/{userID}/schedule", wrapper.GetEventUserSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.GetEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/location", wrapper.CreateLocation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/location/{locationID}", wrapper.GetLocation)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/location/{locationID}", wrapper.UpdateLocation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/location/{locationID}/room", wrapper.CreateRoom)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/location/{locationID}/room/{roomID}", wrapper.DeleteRoom)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/location/{locationID}/room/{roomID}", wrapper.GetRoom)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/location/{locationID}/room/{roomID}", wrapper.UpdateRoom)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/locations", wrapper.GetLocations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/org", wrapper.CreateOrg)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/org/{org}", wrapper.DeleteOrg)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/org/{org}", wrapper.GetOrg)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/org/{org}", wrapper.UpdateOrg)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/org/{org}/events", wrapper.GetOrgEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/org/{org}/members", wrapper.GetOrgMembers)
	})

	return r
}
