FROM docker.io/library/golang:1.25 AS build

WORKDIR /go/src/app
COPY . .

ARG COMMIT_HASH=unknown

RUN go mod tidy
RUN go vet -v
RUN go test -v

RUN CGO_ENABLED=0 go build -ldflags="-s -w -X main.version=${COMMIT_HASH}" -o /go/bin/app

FROM scratch AS prod

COPY --from=build /go/bin/app /
CMD ["/app"]